[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino, espidf
monitor_speed = 115200
board_build.partitions = partitions.csv

; 2. Set your custom flags
build_flags = 
    -D CONFIG_NIMBLE_CPP_IDF=1
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

lib_deps = 
    h2zero/NimBLE-Arduino @ ^1.4.1
    https://github.com/sparkfun/SparkFun_BMV080_Arduino_Library
    Sensirion I2C STCC4
    7Semi BME690
    adafruit/Adafruit MAX1704X@^1.0.3
    GXEPD2
    constiko/RTC RV-3028-C7 Arduino Library@^2.1.0